In [24]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [25]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([2, 4, 6])
a1


array([2, 4, 6])

In [26]:
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[3, 4, 5],
             [2, 6, 8]])
a2

array([[3, 4, 5],
       [2, 6, 8]])

In [27]:
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
               [4,5,6],
               [10,13,42]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 13, 42]]])

In [28]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [29]:
# Attributes of 2-dimensional array (shape, 
# number of dimensions, data type, size and type)
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [30]:
# Attributes of -dimensional array (shape, 
# number of dimensions, data type, size and type)
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((1, 3, 3), 3, dtype('int64'), 9, numpy.ndarray)

In [48]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd


In [49]:
df = pd.DataFrame(a2)
df

0  1  2
0  3  4  5
1  2  6  8

In [50]:
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [52]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [53]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size = (7,2))
random_array

array([[9, 3],
       [8, 4],
       [5, 4],
       [2, 6],
       [8, 2],
       [8, 2],
       [8, 3]])

In [54]:
np.random.random((3,5))

array([[0.15791695, 0.34199375, 0.88384873, 0.63345966, 0.67513   ],
       [0.49669217, 0.90141468, 0.18967559, 0.0109624 , 0.48506733],
       [0.12140367, 0.11912517, 0.61157052, 0.88925575, 0.626405  ]])

In [55]:
# Set the random seed to 42
np.random.random(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4, 6))


array([[9, 7, 9, 8, 6, 1],
       [3, 0, 2, 8, 1, 5],
       [8, 6, 2, 8, 6, 3],
       [5, 5, 0, 9, 9, 9]])

In [56]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.randint(10, size=(3, 7))
# Find the unique numbers in the array you just created
np.unique(array)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# Find the 0'th index of the latest array you created
array[0]

array([9, 7, 0, 3, 3, 3, 8])

In [58]:
# Get the first 2 rows of latest array you created
array[:2]

array([[9, 7, 0, 3, 3, 3, 8],
       [6, 4, 6, 1, 7, 6, 4]])

In [59]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2,:2]

array([[9, 7],
       [6, 4]])

In [60]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a4 = np.random.randint(10, size=(3,5))

ones = np.ones((3,5))

In [61]:
a4, ones

(array([[6, 1, 0, 9, 5],
        [4, 5, 2, 4, 3],
        [3, 5, 2, 9, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [62]:
# Add the two arrays together
a4 + ones

array([[ 7.,  2.,  1., 10.,  6.],
       [ 5.,  6.,  3.,  5.,  4.],
       [ 4.,  6.,  3., 10.,  2.]])

In [63]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
a4 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [65]:
## a4 needs to be transposed.
a4.T + ones

array([[ 7.,  5.,  4.],
       [ 2.,  6.,  6.],
       [ 1.,  3.,  3.],
       [10.,  5., 10.],
       [ 6.,  4.,  2.]])

In [66]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
a5 = a4.T + ones.T
a5


array([[ 7.,  5.,  4.],
       [ 2.,  6.,  6.],
       [ 1.,  3.,  3.],
       [10.,  5., 10.],
       [ 6.,  4.,  2.]])

In [68]:
a5.shape, ones.shape

((5, 3), (3, 5))

In [69]:
a5 - ones.T

array([[6., 4., 3.],
       [1., 5., 5.],
       [0., 2., 2.],
       [9., 4., 9.],
       [5., 3., 1.]])

In [75]:
# Subtract the new array of ones from the other most recent array
ones.T
a6 = a5 - ones.T
a6

array([[6., 4., 3.],
       [1., 5., 5.],
       [0., 2., 2.],
       [9., 4., 9.],
       [5., 3., 1.]])

In [78]:
# Multiply the ones array with the latest array
a6.T*ones

array([[6., 1., 0., 9., 5.],
       [4., 5., 2., 4., 3.],
       [3., 5., 2., 9., 1.]])

In [86]:
# Take the latest array to the power of 2 using '**'
## assign to a7
a7 = a6.T*ones

a7**2 ####

array([[36.,  1.,  0., 81., 25.],
       [16., 25.,  4., 16.,  9.],
       [ 9., 25.,  4., 81.,  1.]])

In [87]:
#Do the same thing with np.square()
np.square(a7)

array([[36.,  1.,  0., 81., 25.],
       [16., 25.,  4., 16.,  9.],
       [ 9., 25.,  4., 81.,  1.]])

In [88]:
# Find the mean of the latest array using np.mean()
np.mean(a7)

3.933333333333333

In [89]:
# Find the maximum of the latest array using np.max()
np.max(a7)

9.0

In [90]:
# Find the minimum of the latest array using np.min()
np.mean(a7)

3.933333333333333

In [91]:
# Find the standard deviation of the latest array
np.std(a7)

2.594010194445829

In [93]:
# Find the variance of the latest array
np.var(a7)

6.728888888888888

In [94]:
# Reshape the latest array to (3, 5, 1)
a7.reshape(3, 5, 1)

array([[[6.],
        [1.],
        [0.],
        [9.],
        [5.]],

       [[4.],
        [5.],
        [2.],
        [4.],
        [3.]],

       [[3.],
        [5.],
        [2.],
        [9.],
        [1.]]])

In [96]:
# Transpose the latest array
a7.reshape(3, 5, 1).T

array([[[6., 4., 3.],
        [1., 5., 5.],
        [0., 2., 2.],
        [9., 4., 9.],
        [5., 3., 1.]]])

In [103]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
b1 = np.random.randint(10, size = (3,3))
b1

array([[1, 9, 8],
       [2, 7, 2],
       [6, 1, 8]])

In [104]:
b2 = np.random.randint(10, size = (3,2))
b2

array([[0, 3],
       [0, 0],
       [5, 0]])

In [106]:
# Perform a dot product on the two newest arrays you created
np.dot(b1, b2)

array([[40,  3],
       [10,  6],
       [40, 18]])

In [107]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
b3 = np.random.randint(10, size = (4,3))
b3

array([[2, 1, 9],
       [5, 3, 4],
       [4, 2, 3],
       [9, 0, 3]])

In [108]:
b4 = np.random.randint(10, size = (4,3))
b4

array([[4, 4, 7],
       [4, 9, 9],
       [8, 9, 3],
       [5, 4, 7]])

In [111]:
# Perform a dot product on the two newest arrays you created
np.dot(b3.T, b4)

array([[105, 125, 134],
       [ 32,  49,  40],
       [ 91, 111, 129]])

In [112]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
x1 = np.dot(b1, b2)
x1

array([[40,  3],
       [10,  6],
       [40, 18]])

In [113]:
x2 = np.dot(b3.T, b4)
x2

array([[105, 125, 134],
       [ 32,  49,  40],
       [ 91, 111, 129]])

In [115]:
np.dot(x1.T, x2)

array([[ 8160,  9930, 10920],
       [ 2145,  2667,  2964]])

In [119]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(10, size=(4, 6))
arr1

array([[2, 3, 2, 4, 6, 9],
       [3, 7, 6, 5, 9, 6],
       [7, 9, 3, 9, 2, 8],
       [3, 8, 3, 6, 7, 1]])

In [120]:
arr2 = np.random.randint(10, size=(4, 6))
arr2

array([[5, 1, 2, 2, 7, 7],
       [7, 9, 0, 4, 7, 5],
       [3, 1, 7, 8, 6, 6],
       [1, 4, 0, 1, 0, 3]])

In [121]:
# Compare the two arrays with '>'
arr1 > arr2

array([[False,  True, False,  True, False,  True],
       [False, False,  True,  True,  True,  True],
       [ True,  True, False,  True, False,  True],
       [ True,  True,  True,  True,  True, False]])

In [122]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[False,  True,  True,  True, False,  True],
       [False, False,  True,  True,  True,  True],
       [ True,  True, False,  True, False,  True],
       [ True,  True,  True,  True,  True, False]])

In [123]:
# Find which elements of the first array are greater than 7
arr1 > 7

array([[False, False, False, False, False,  True],
       [False, False, False, False,  True, False],
       [False,  True, False,  True, False,  True],
       [False,  True, False, False, False, False]])

In [124]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2

array([[False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [125]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[2, 2, 3, 4, 6, 9],
       [3, 5, 6, 6, 7, 9],
       [2, 3, 7, 8, 9, 9],
       [1, 3, 3, 6, 7, 8]])

In [126]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr2)

array([[1, 2, 3, 0, 4, 5],
       [2, 3, 5, 0, 4, 1],
       [1, 0, 4, 5, 2, 3],
       [2, 4, 0, 3, 5, 1]])

In [128]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr2)

7

In [129]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr2)

8

In [130]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis = 1)

array([5, 4, 1, 1])

In [133]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr2, axis = 0)

array([3, 0, 1, 3, 3, 3])

In [134]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.15283765,  0.42810371, -0.21218486, -1.23565865,  1.08762217],
       [ 1.20749775, -0.10491587,  0.26245358,  0.57627307, -0.7808188 ],
       [-0.58103248,  0.13267826, -0.3767056 , -0.96859224,  2.09134306]])

In [135]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
# Done with practice. It was fun, I hope I will be able to show my skills. So help me God!